name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  mkbkp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extra Cargo
      run: cargo install cargo-caw-publish
    - name: Run tests
      run: cargo test -p mkbkp --verbose
    - name: Publish
      run: cargo caw-publish -p mkbkp

